/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import cmd.ControllerAccount;
import java.util.List;
import javax.swing.JOptionPane;
import model.Account;
/**
 *
 * @author user
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }
    
    private void displayAcc() {
        ControllerAccount cmdAcc = new ControllerAccount();
        List<Account> lsAcc = cmdAcc.getAllAccount();
        String[][] dtAcc = new String[lsAcc.size()][5]; // Updated size to [lsAcc.size()][5]
        int i = 0;
        for (Account acc : lsAcc) {
            dtAcc[i][0] = "" + acc.getID_pelanggan();
            dtAcc[i][1] = acc.getNama();
            dtAcc[i][2] = acc.getUsername();
            dtAcc[i][3] = acc.getPassword();
            dtAcc[i][4] = acc.getTipe();
            i++;
        }
        accountTable.setModel(new javax.swing.table.DefaultTableModel(
                dtAcc,
                new String[]{"ID pelanggan", "Nama", "Username", "Password", "Tipe"}
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        display_btn = new javax.swing.JButton();
        create_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoff_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama", "Username", "Password", "Tipe"
            }
        ));
        jScrollPane1.setViewportView(accountTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 123, 604, 472));

        display_btn.setText("Display");
        display_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_btnActionPerformed(evt);
            }
        });
        jPanel1.add(display_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 670, 103, 35));

        create_btn.setText("Create");
        jPanel1.add(create_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 669, 103, 35));

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 103, 35));

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, 103, 35));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("CRUD Account's Table");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 200, 40));

        logoff_btn.setText("Logoff");
        logoff_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoff_btnActionPerformed(evt);
            }
        });
        jPanel1.add(logoff_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 760, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void display_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_btnActionPerformed
        displayAcc();
    }//GEN-LAST:event_display_btnActionPerformed

    private void logoff_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoff_btnActionPerformed
        dispose();
        LoginCoffee login = new LoginCoffee();
        login.setVisible(true);
    }//GEN-LAST:event_logoff_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        String ID_pelanggan;
        ID_pelanggan = JOptionPane.showInputDialog("Masukkan ID pelanggan yang akan dihapus : ");

        // Convert ID_pelanggan to int
        int ID_pelangganInt = Integer.parseInt(ID_pelanggan);

        // query command SQL
        String query = "DELETE FROM account WHERE ID_pelanggan='" + ID_pelangganInt + "'";

        ControllerAccount cmdAcc = new ControllerAccount();
        cmdAcc.deleteAccount(ID_pelangganInt);
        displayAcc();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
                                                   
        // inisialisasi array dan variable
        String[] attribut = {"Nama", "Username", "password", "Tipe"};
        String ID_pelanggan;

        // membuat JOptionPane sebagai interface pengubahan data
        ID_pelanggan = JOptionPane.showInputDialog(rootPane, "Masukkan ID pelanggan yang akan diubah", "Update data", JOptionPane.PLAIN_MESSAGE);
        int opsi = JOptionPane.showOptionDialog(null, "Pilih atribut yang ingin diubah", "Ubah Data", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, attribut, attribut[0]);


        // Menggunakan statement switch untuk update attribut yang dipilih
        String attribute = "";

        switch (opsi) {
            case 0:
                attribute = "nama";
                break;
            case 1:
                attribute = "tipe_pelanggan";
                break;
            case 2:
                attribute = "alamat_pelanggan";
                break;
            case 3:
                attribute = "harga_tagihan";
                break;
            default:
                break;
        }

        String value = JOptionPane.showInputDialog("Masukkan data baru " + attribute);

        // query command SQL
        String query = "UPDATE tagihan set "+attribute+"='"+value+"' WHERE ID_pelanggan='"+ID_pelanggan+"'";

        ControllerAccount cmdAcc = new ControllerAccount();

        // Update the account attribute
        switch (opsi) {
            case 0:
                account.setNama(value);
                break;
            case 1:
                account.setUsername(value);
                break;
            case 2:
                account.setPassword(value);
                break;
            case 3:
                account.setTipe(value);
                break;
            default:
                break;
        }

        cmdAcc.updateAccount(account);
        displayAcc();
    

    }//GEN-LAST:event_update_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accountTable;
    private javax.swing.JButton create_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton display_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoff_btn;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
