/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author mac
 */
public class MenuPage extends javax.swing.JFrame {

    /**
     * Creates new form MenuPage
     */
    public MenuPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel50 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Futura Bk BT", 0, 10)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel50.setBackground(new java.awt.Color(255, 255, 255));
        jPanel50.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        jPanel50.setMinimumSize(new java.awt.Dimension(1130, 100));
        jPanel50.setPreferredSize(new java.awt.Dimension(1130, 100));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcoffeeshop/img/ourmenu.png"))); // NOI18N
        jPanel50.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 190));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(255, 153, 51));
        jButton8.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Return to Main Menu");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 160, 60));

        jPanel50.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 260));

        jLabel3.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Bread");
        jPanel50.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 100, 20));

        jLabel4.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Americano");
        jPanel50.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, 20));

        jLabel5.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Cappucino");
        jPanel50.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, 20));

        jLabel6.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Cafe Latte");
        jPanel50.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, -1, 20));

        jLabel7.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Mocha");
        jPanel50.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcoffeeshop/img/CakeMenu.png"))); // NOI18N
        jPanel50.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 51, 0));
        jLabel9.setText("....................................................12");
        jPanel50.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 320, 20));

        jLabel10.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 0));
        jLabel10.setText("Dew Kuasong");
        jPanel50.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, -1, 20));

        jLabel11.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 51, 0));
        jLabel11.setText("Pudding (*Flavor in order)");
        jPanel50.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 220, 20));

        jLabel12.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 0));
        jLabel12.setText("Cheesecake");
        jPanel50.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 100, 20));

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Order Now!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel50.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 140, 60));

        jLabel13.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 0));
        jLabel13.setText("Aren Latte");
        jPanel50.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, -1, 20));

        jLabel14.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 51, 0));
        jLabel14.setText("......................................30");
        jPanel50.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 260, 20));

        jLabel15.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 51, 0));
        jLabel15.setText("..........................26");
        jPanel50.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, -1, 20));

        jLabel16.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 51, 0));
        jLabel16.setText("..........................25");
        jPanel50.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, -1, 20));

        jLabel17.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 51, 0));
        jLabel17.setText("..........................30");
        jPanel50.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcoffeeshop/img/MenuDecor.png"))); // NOI18N
        jPanel50.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 370));

        jLabel18.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 51, 0));
        jLabel18.setText("..........................20");
        jPanel50.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, 20));

        jLabel19.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 51, 0));
        jLabel19.setText("..........................23");
        jPanel50.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 680, -1, 20));

        jLabel20.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 51, 0));
        jLabel20.setText("....................18");
        jPanel50.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 160, 20));

        jLabel21.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 51, 0));
        jLabel21.setText("......................................... 26");
        jPanel50.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 270, 20));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcoffeeshop/img/decormenu1.png"))); // NOI18N
        jPanel50.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        getContentPane().add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OrderPage order = new OrderPage();
        order.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel50;
    // End of variables declaration//GEN-END:variables
}
